done tasks from stałe i adnotacje
Kruz00/pio_git_rhymers pull request #1
Opened 2022-01-23 23:14 UTC by VermiIion

2022-01-23 23:48 UTC, Kruz00 requested changes
kilka zmian do zrobienia, masz komentarze co i jak

2022-01-23 23:48 UTC, Kruz00 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +		return total == size-empty;
zła logika, bo wychodzi 13, i nie może być size-empty, już lepiej size-1 lub inna stała =size-1

2022-01-23 23:48 UTC, Kruz00 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	final static int size = 12;
nazwy stałych wielkimi literami

2022-01-23 23:48 UTC, Kruz00 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	final static int size = 12;
to ma być max liczba elementów w tablicy, nazwij trochę dokładniej

2022-01-23 23:48 UTC, Kruz00 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	final static int size = 12;
Stale daj na sam początek

2022-01-23 23:48 UTC, Kruz00 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	final static int empty = -1;
wielkimi literami

2022-01-23 23:48 UTC, Kruz00 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +			return empty;
nie zwracasz empty tylko error code jakiegoś, zrób inna stałą z dobrą nazwą

2022-01-23 23:48 UTC, Kruz00 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +			return empty;
to samo co w 27 linii

2022-01-23 23:48 UTC, Kruz00 commented on src/main/java/edu/kis/vh/nursery/HanoiRhymer.java
> +	@Override public void countIn(int in) {
@Override daj w osobnej linii wcześniej

2022-01-24 00:06 UTC, VermiIion commented
Poprawione szefie B-)

2022-01-24 00:16 UTC, Kruz00 approved these changes
gitara dziena

2022-01-24 00:17 UTC, merged